{{- if .Values.localstack.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ark.localstackServiceName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ark.labels" . | nindent 4 }}
    app.kubernetes.io/component: localstack
spec:
  type: ClusterIP
  selector:
    {{- include "ark.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: localstack
  ports:
    - name: edge
      port: 4566
      targetPort: edge
      protocol: TCP
{{- end }}
