{{- if and .Values.temporal.enabled .Values.externalSecret.enabled .Values.temporal.persistence.secretManagerKey }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.temporal.persistence.existingSecret }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "ark.labels" . | nindent 4 }}
    app.kubernetes.io/component: temporal-db-credentials
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.storeName | default "aws-secretstore" }}
    kind: {{ .Values.externalSecret.storeKind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.temporal.persistence.existingSecret }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.temporal.persistence.secretKeys.username | quote }}
      remoteRef:
        key: {{ .Values.temporal.persistence.secretManagerKey | quote }}
        property: {{ .Values.temporal.persistence.secretKeys.username | quote }}
    - secretKey: {{ .Values.temporal.persistence.secretKeys.password | quote }}
      remoteRef:
        key: {{ .Values.temporal.persistence.secretManagerKey | quote }}
        property: {{ .Values.temporal.persistence.secretKeys.password | quote }}
{{- end }}
